version: 2

models:
  - name: sales_orders_cleaned
    description: has to have order_number
    columns:
      - name: order_number
        description: order_number should not be null
        tests:
          - not_null
  - name: sales_order_in_chicago
    description: has to have customer_id
    columns:
      - name: customer_id
        description: customer_id should not be null
        tests:
          - not_null
  - name: sales_order_in_la
    description: has to have customer_id
    columns:
      - name: customer_id
        description: customer_id should not be null
        tests:
          - not_null
