version: 2

models:
  - name: sales_orders_cleaned
    description: has to have order_number
    columns:
      - name: order_number
        description: order_number should not be null
        tests:
          - not_null
